### ISSUE TITLE
Autopsy 4.21.0

### ISSUE THREAD

**Issue by Gerd1986** [markmckinnon/Autopsy-NBM-Plugins#2]
Hey Mark
It Doesnt Seem to work for this Version 😔

**Comment by markmckinnon** [comment]
Which one are you looking at?

**Comment by Gerd1986** [comment]
Hi Mark
The vleapp 
No matter if i have an Image or logical file dump it wont produce results. With the standalone vleapp it does.

**Comment by Gerd1986** [comment]
Now its working. I had to have Admin rights and use an Image or a zip. I was Even able to change the exe to Support my artifact adaptations. Sorry for the alert but this might save others. Great work!
Cheers 
Gerd
